image: python:3.6

stages:
  - build
  - deploy

before_script:
  - pip install sphinx
# test:
#   stage: test
#   tags:
#     - dspsr
#   script:
#     - dspsr --version

pages:
  stage: deploy
  script:
    - echo "hello"

build_pages:
  stage: build
  script:
    - echo "hello"
