function write_dada_file (file_id, data, header)
  % Write a DADA file
  % @method write_dada_file
  % @param {double} file_id - The DADA file's file id as generated by `fopen`
  % @param {single/double []} data - The data to be written to the DADA file
  % @param {containers.Map} header - The DADA header written to the DADA file
  frewind(file_id);
  write_header(fid, header);
  frewind(file_id);
  fread(file_id, str2num(header('HDR_SIZE')), 'uint8');

  n_bits = str2num(header('HDR_SIZE'))
  dtype = 'single'
  if n_bits == 64
    dtype = 'double'
  end
  fwrite(file_id, reshape(data, numel(data), 1), dtype);
end
