function hdr_map = read_header(file_id)
  % given some filename or file id, read in the DADA header information
  %
  % Args:
  %   file_id (double): The file id generated by fopen
  % Returns:
  %   containers.Map: map object containing header information from file

  formatter = '%c';
  % fprintf('read_header\n');

  function hdr_map_ = read_header_ (hdr_size_)
    frewind(file_id);
    % fprintf('read_header_: hdr_size_: %d\n', hdr_size_);
    hdr_map_ = containers.Map();
    header_str = fscanf(file_id, formatter, hdr_size_);
    header_lines = strsplit(header_str, '\n');
    for i=1:length(header_lines)
      line = header_lines{i} ;
      if startsWith(line, '#')
        continue
      end

      keyValPair = strsplit(header_lines{i});
      if length(keyValPair) > 1
        hdr_map_(keyValPair{1}) = keyValPair{2};
      end
    end
    if isKey(hdr_map_, 'HDR_SIZE')
      new_hdr_size = str2num(hdr_map_('HDR_SIZE'));
      if new_hdr_size ~= hdr_size_
        hdr_map_ = read_header_ (new_hdr_size);
      end
    else
      hdr_map_ = read_header_ (hdr_size_ * 2);
    end
  end

  hdr_map = read_header_(4096);

end
