function write_dada_data (file_id, data, verbose_)
  % Write data to a DADA file
  % 
  % Args:
  %   file_id (double): The DADA file's file id as generated by `fopen`
  %   data ([numeric]): The data to be written to the DADA file

  % make sure that the data characterisitcs in the header are correct
  verbose = 0;
  if exist('verbose_', 'var')
    verbose = verbose_;
  end

  dtype = class(data);

  bytes_per_element = 8;
  if dtype == "single"
    bytes_per_element = 4;
  elseif dtype == "uint8" || dtype == "int16"
    bytes_per_element = 2;
  elseif dtype == "uint8" || dtype == "int8"
    bytes_per_element = 1;
  end

  if verbose
    fprintf('write_dada_data: dtype=%s\n', dtype);
  end

  % input data are in PFT order; this flattens them to TFP
  data = reshape(data, [], 1);

  if ~isreal(data)
    temp = zeros(2*numel(data), 1, dtype);
    temp(1:2:end,1) = real(data);
    temp(2:2:end,1) = imag(data);
    data = temp;
  end

  ptr1=ftell(file_id);
  fwrite(file_id, data, dtype);
  ptr2=ftell(file_id);

  if (ptr2 - ptr1) ~= numel(data) * bytes_per_element
    fprintf ('unexpected fptr bytes=%d ptr1=%d ptr2=%d diff=%d\n', ...
        numel(data)*4, ptr1, ptr2, ptr2-ptr1);
    error ('Incorrect file pointer after writing data');
  end

end
