function write_dada_data (file_id, data, verbose_)
  % Write data to a DADA file
  % 
  % Args:
  %   file_id (double): The DADA file's file id as generated by `fopen`
  %   data ([numeric]): The data to be written to the DADA file

  verbose = 0;
  if exist('verbose_', 'var')
    verbose = verbose_;
  end

  dtype = class(data);

  bytes_per_element = 8;
  if dtype == "single"
    bytes_per_element = 4;
  elseif dtype == "uint16" || dtype == "int16"
    bytes_per_element = 2;
  elseif dtype == "uint8" || dtype == "int8"
    bytes_per_element = 1;
  end

  if verbose || bytes_per_element ~= 4
    fprintf('write_dada_data: dtype=%s bytes=%d\n', dtype, bytes_per_element);
  end

  if isreal(data)
     error ('write_dada_data: unexpected real-valued input data');
  end

  % input data are in PFT order; this flattens them to TFP
  data = reshape(data, [], 1);

  % convert complex-valued to real-valued (real,imag interleaved)
  if ~isreal(data)
    temp = zeros(2*numel(data), 1, dtype);
    temp(1:2:end,1) = real(data);
    temp(2:2:end,1) = imag(data);
    data = temp;
  else
      error ('write_dada_data: unexpected real-valued data after reshape');
  end

  ptr1=ftell(file_id);
  fwrite(file_id, data, dtype);
  ptr2=ftell(file_id);

  expected_offset = numel(data) * bytes_per_element;
  if (ptr2 - ptr1) ~= expected_offset
    fprintf ('unexpected fptr bytes=%d ptr1=%d ptr2=%d diff=%d\n', ...
        expected_offset, ptr1, ptr2, ptr2-ptr1);
    error ('Incorrect file pointer after writing data');
  end

end
