function write_dada_header (file_id, data, header, verbose_)
  % Write a DADA header to file
  % 
  % Args:
  %   file_id (double): The DADA file's file id as generated by `fopen`
  %   data ([numeric]): The data to be written to the DADA file
  %   header (containers.Map): The DADA header written to the DADA file

  % make sure that the data characterisitcs in the header are correct
  verbose = 0;
  if exist('verbose_', 'var')
    verbose = verbose_;
  end

  header('NBIT') = '64';
  if class(data) == "single"
    header('NBIT') = '32';
  elseif class(data) == "uint8" || class(data) == "int8"
    header('NBIT') = '8';
  end

  header('NDIM') = '2';
  if isreal(data)
    header('NDIM') = '1';
  end

  size_data = size(data);
  header('NPOL') = num2str(size_data(1));
  header('NCHAN') = num2str(size_data(2));

  % ensure we're at the start of the file
  frewind(file_id);
  % fprintf ('after frewind, file pointer at %d\n', ftell(file_id));
  write_header(file_id, header);

end
